const express = require('express');
const mjml2html = require('mjml');
const archiver = require('archiver');
const { generateMJML } = require('../utils/mjmlGenerator');
const { validateLicense } = require('../services/licenseStore');

const router = express.Router();

// ── HTML-only export (preview) ────────────────────────────────────
router.post('/', (req, res) => {
  const { mjml, minify = false } = req.body;
  if (!mjml) return res.status(400).json({ error: 'mjml field is required' });

  try {
    const result = mjml2html(mjml, { validationLevel: 'soft', minify });
    res.json({ html: result.html, warnings: result.errors?.map(e => e.message) || [] });
  } catch (err) {
    console.error('MJML error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── ZIP export with assets folder ─────────────────────────────────
router.post('/zip', express.json({ limit: '150mb' }), async (req, res) => {
  const { blocks = [], globalSettings = {}, subject = 'email', licenseKey = '' } = req.body;
  const key = licenseKey || req.headers['x-license-key'];
  const access = validateLicense(key);
  if (!access.valid) {
    return res.status(402).json({
      error: access.reason || 'A paid Emailix license is required to download templates.',
      plans: [
        { id: 'monthly', price: 29, label: 'Monthly' },
        { id: 'yearly', price: 199, label: 'Yearly' },
      ],
    });
  }

  try {
    const assets = [];

    // Deep-clone blocks and extract base64 images into asset files
    const processedBlocks = JSON.parse(JSON.stringify(blocks)).map(block => {
      const imageProps = getImageProps(block.type);
      for (const propKey of imageProps) {
        const val = block.props[propKey];
        if (val && val.startsWith('data:')) {
          const match = val.match(/^data:([^;]+);base64,(.+)$/s);
          if (match) {
            const mime = match[1];
            const ext = mime.split('/')[1].replace('jpeg', 'jpg').split('+')[0].split(';')[0];
            const n = assets.length + 1;
            const filename = `image-${n}.${ext}`;
            assets.push({ filename, buffer: Buffer.from(match[2], 'base64') });
            block.props[propKey] = `assets/${filename}`;
          }
        }
      }
      return block;
    });

    // Generate and compile MJML
    const mjml = generateMJML(processedBlocks, globalSettings);
    const compiled = mjml2html(mjml, { validationLevel: 'soft', minify: false });
    const html = compiled.html;

    // Stream ZIP response
    const safeName = subject.replace(/[^a-z0-9_-]/gi, '_') || 'email';
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}.zip"`);

    const archive = archiver('zip', { zlib: { level: 6 } });
    archive.on('error', err => { throw err; });
    archive.pipe(res);

    archive.append(html, { name: `${safeName}.html` });

    for (const asset of assets) {
      archive.append(asset.buffer, { name: `assets/${asset.filename}` });
    }

    // Add a readme
    const readme = `Email Template: ${subject}
Generated by Emailix
Plan: ${access.license.plan}

Files:
  ${safeName}.html   - The email HTML file
  assets/            - Image assets referenced in the email

To use:
  1. Upload the assets/ folder to your server or CDN
  2. Update image src paths in ${safeName}.html to point to your hosted URLs
  3. Or keep the assets/ folder alongside the HTML for local preview

Note: Open ${safeName}.html in a browser to preview the email.
`;
    archive.append(readme, { name: 'README.txt' });

    await archive.finalize();
  } catch (err) {
    console.error('ZIP export error:', err.message);
    if (!res.headersSent) {
      res.status(500).json({ error: err.message });
    }
  }
});

function getImageProps(type) {
  const map = {
    logo: ['src'],
    image: ['src'],
    video: ['thumbnailSrc'],
  };
  return map[type] || [];
}

module.exports = router;
