const express = require('express');
const mjml2html = require('mjml');
const archiver = require('archiver');
const { generateMJML } = require('../utils/mjmlGenerator');
const { validateLicense } = require('../services/licenseStore');

const router = express.Router();

// ── HTML-only export (preview) ────────────────────────────────────
router.post('/', (req, res) => {
  const { mjml, minify = false } = req.body;
  if (!mjml) return res.status(400).json({ error: 'mjml field is required' });

  try {
    const result = mjml2html(mjml, { validationLevel: 'soft', minify });
    res.json({ html: result.html, warnings: result.errors?.map(e => e.message) || [] });
  } catch (err) {
    console.error('MJML error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── ZIP export with HTML and images folder ────────────────────────
router.post('/zip', express.json({ limit: '150mb' }), async (req, res) => {
  const { blocks = [], globalSettings = {}, subject = 'email', licenseKey = '' } = req.body;
  const key = licenseKey || req.headers['x-license-key'];
  const access = validateLicense(key);
  if (!access.valid) {
    return res.status(402).json({
      error: access.reason || 'A paid Emailix license is required to download templates.',
      plans: [
        { id: 'pro', price: 15, label: 'Pro' },
        { id: 'team', price: 39, label: 'Team' },
      ],
    });
  }

  try {
    const { processedBlocks, images } = prepareBlocksForZip(blocks);

    // Generate and compile MJML
    const mjml = generateMJML(processedBlocks, globalSettings);
    const compiled = mjml2html(mjml, { validationLevel: 'soft', minify: false });
    const html = compiled.html;

    // Stream ZIP response
    const safeName = subject.replace(/[^a-z0-9_-]/gi, '_') || 'email';
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}.zip"`);

    const archive = archiver('zip', { zlib: { level: 6 } });
    archive.on('error', err => { throw err; });
    archive.pipe(res);

    archive.append(html, { name: `${safeName}.html` });
    archive.append('', { name: 'images/' });

    for (const image of images) {
      archive.append(image.buffer, { name: `images/${image.filename}` });
    }

    // Add a readme
    const readme = `Email Template: ${subject}
Generated by Emailix
Plan: ${access.license.plan}

Files:
  ${safeName}.html   - The email HTML file
  images/            - Uploaded image assets referenced by the HTML

To use:
  1. Keep ${safeName}.html and the images/ folder together when importing
  2. Upload the images/ folder to your email broadcaster, CDN, or server
  3. If your broadcaster does not support relative image paths, replace images/... paths in ${safeName}.html with the hosted image URLs

Note: Uploaded images are packaged locally. External image URLs stay unchanged.
`;
    archive.append(readme, { name: 'README.txt' });

    await archive.finalize();
  } catch (err) {
    console.error('ZIP export error:', err.message);
    if (!res.headersSent) {
      res.status(500).json({ error: err.message });
    }
  }
});

function prepareBlocksForZip(blocks) {
  const images = [];
  const seenImages = new Map();
  const processedBlocks = replaceDataImages(JSON.parse(JSON.stringify(blocks)), images, seenImages);
  return { processedBlocks, images };
}

function replaceDataImages(value, images, seenImages) {
  if (typeof value === 'string') return replaceDataImageStrings(value, images, seenImages);
  if (Array.isArray(value)) return value.map(item => replaceDataImages(item, images, seenImages));
  if (value && typeof value === 'object') {
    for (const key of Object.keys(value)) {
      value[key] = replaceDataImages(value[key], images, seenImages);
    }
  }
  return value;
}

function replaceDataImageStrings(value, images, seenImages) {
  return value.replace(/data:image\/([a-z0-9.+-]+);base64,([a-z0-9+/=]+)/gi, (match, subtype, base64) => {
    if (seenImages.has(match)) return `images/${seenImages.get(match)}`;

    const filename = `image-${images.length + 1}.${extensionForImageSubtype(subtype)}`;
    seenImages.set(match, filename);
    images.push({ filename, buffer: Buffer.from(base64, 'base64') });
    return `images/${filename}`;
  });
}

function extensionForImageSubtype(subtype) {
  const normalized = String(subtype || '').toLowerCase();
  if (normalized === 'jpeg' || normalized === 'pjpeg') return 'jpg';
  if (normalized === 'svg+xml') return 'svg';
  if (normalized === 'x-icon' || normalized === 'vnd.microsoft.icon') return 'ico';
  return normalized.split('+')[0].replace(/[^a-z0-9]/g, '') || 'png';
}

module.exports = router;
